configuration: Release

branches:
  only:
    - master

build:
  verbosity: minimal

deploy:
  tag: LatestCommit
  release: Smash Forge [Latest Commit]
  description: 'This build is updated every time a commit is pushed.\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token:
    secure: 4ebqOCir67guBkJ24KTokNSNVkW0E36XGG+xLwDcNQ16W3+0Uon0zB21H6OPS020
  artifact: Smash-Forge-Latest_Commit.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

  
after_build:
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\VBN Editor\bin\Release\VBN Editor.exe"
  - 7z a "Smash-Forge-Latest_Commit.zip" "VBN Editor\bin\Release\lib\*.dll"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\VBN Editor\bin\Release\*.csv"
  - appveyor PushArtifact "Smash-Forge-Latest_Commit.zip"
