configuration: Release

image:
  - Visual Studio 2017

branches:
  only:
    - master

before_build:
- cmd: cd SFGraphics
- ps: nuget restore
- cmd: cd ..

build:
  verbosity: minimal

build_script:
  - msbuild "SFGraphics/SFGraphics.sln"
  - tree
  - copy /Y "%APPVEYOR_BUILD_FOLDER%\SFGraphics\src\SFGraphics\bin\Release\SFGraphics.dll" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\lib\"
  - copy /Y "%APPVEYOR_BUILD_FOLDER%\SFGraphics\src\SFGraphics\bin\Release\SFGraphics.xml" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\lib\"
  - msbuild "Smash Forge.sln"

deploy:
  tag: LatestCommit
  release: Smash Forge [Latest Commit]
  description: 'This build is updated every time a commit is pushed.\n\n$(APPVEYOR_REPO_COMMIT_MESSAGE)\n\n Timestamp: $(APPVEYOR_REPO_COMMIT_TIMESTAMP)'
  provider: GitHub
  auth_token:
    secure: 4ebqOCir67guBkJ24KTokNSNVkW0E36XGG+xLwDcNQ16W3+0Uon0zB21H6OPS020
  artifact: Smash-Forge-Latest_Commit.zip
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: master

install:
  - git submodule update --init --recursive

test:
  assemblies:
    except:
    - 'SFGraphics\test\SFGraphicsRenderTests\bin\Release\SFGraphicsRenderTests.dll'

after_build:
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\Smash Forge.exe"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\Smash Forge.exe.config"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\lib\"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\*.csv"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\materials"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\param_labels"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Smash Forge\bin\Release\Preview Images"
  - 7z a "Smash-Forge-Latest_Commit.zip" "%APPVEYOR_BUILD_FOLDER%\Forge Updater\bin\Release\updater"
  - appveyor PushArtifact "Smash-Forge-Latest_Commit.zip"
